language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - "node"
after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - npm run docs
  - npm run build
  - npm run travis-deploy-once "npm run semantic-release"
  - curl -Is https://purge.jsdelivr.net/npm/dinero.js/build/umd/dinero.min.js
branches:
  only:
    - master
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_DEPLOY_TOKEN
  keep-history: true
  target-branch: master
  on:
    branch: master
