language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - "node"
after_success:
  - tasks/after_success.sh
branches:
  only:
    - master
    - develop
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_DEPLOY_TOKEN
  keep-history: true
  target-branch: master
  on:
    branch: master
